/**
 * IDL type for the FutureBit Staking Program.
 * Generated by `anchor build` and placed here for frontend consumption.
 * Replace this placeholder with the actual IDL after `anchor build`.
 */
export type Staking = {
  version: "0.1.0";
  name: "staking";
  instructions: [
    {
      name: "initialize";
      accounts: [
        { name: "admin"; isMut: true; isSigner: true },
        { name: "tokenMint"; isMut: false; isSigner: false },
        { name: "platformState"; isMut: true; isSigner: false },
        { name: "vault"; isMut: true; isSigner: false },
        { name: "rewardVault"; isMut: true; isSigner: false },
        { name: "tokenProgram"; isMut: false; isSigner: false },
        { name: "systemProgram"; isMut: false; isSigner: false },
        { name: "rent"; isMut: false; isSigner: false }
      ];
      args: [{ name: "baseApyBps"; type: "u64" }];
    },
    {
      name: "stake";
      accounts: [
        { name: "user"; isMut: true; isSigner: true },
        { name: "platformState"; isMut: true; isSigner: false },
        { name: "userStakeAccount"; isMut: true; isSigner: false },
        { name: "userTokenAccount"; isMut: true; isSigner: false },
        { name: "vault"; isMut: true; isSigner: false },
        { name: "referrerStakeAccount"; isMut: false; isSigner: false },
        { name: "tokenProgram"; isMut: false; isSigner: false },
        { name: "systemProgram"; isMut: false; isSigner: false }
      ];
      args: [
        { name: "amount"; type: "u64" },
        { name: "lockPeriodSecs"; type: "u64" },
        { name: "referrer"; type: { option: "publicKey" } }
      ];
    },
    {
      name: "unstake";
      accounts: [
        { name: "user"; isMut: true; isSigner: true },
        { name: "platformState"; isMut: true; isSigner: false },
        { name: "userStakeAccount"; isMut: true; isSigner: false },
        { name: "vault"; isMut: true; isSigner: false },
        { name: "rewardVault"; isMut: true; isSigner: false },
        { name: "userTokenAccount"; isMut: true; isSigner: false },
        { name: "tokenProgram"; isMut: false; isSigner: false }
      ];
      args: [];
    },
    {
      name: "claimRewards";
      accounts: [
        { name: "user"; isMut: true; isSigner: true },
        { name: "platformState"; isMut: true; isSigner: false },
        { name: "userStakeAccount"; isMut: true; isSigner: false },
        { name: "rewardVault"; isMut: true; isSigner: false },
        { name: "userTokenAccount"; isMut: true; isSigner: false },
        { name: "tokenProgram"; isMut: false; isSigner: false }
      ];
      args: [];
    },
    {
      name: "compound";
      accounts: [
        { name: "user"; isMut: true; isSigner: true },
        { name: "platformState"; isMut: true; isSigner: false },
        { name: "userStakeAccount"; isMut: true; isSigner: false }
      ];
      args: [];
    },
    {
      name: "fundRewardPool";
      accounts: [
        { name: "admin"; isMut: true; isSigner: true },
        { name: "platformState"; isMut: true; isSigner: false },
        { name: "rewardVault"; isMut: true; isSigner: false },
        { name: "adminTokenAccount"; isMut: true; isSigner: false },
        { name: "tokenProgram"; isMut: false; isSigner: false }
      ];
      args: [{ name: "amount"; type: "u64" }];
    },
    {
      name: "setRewardRate";
      accounts: [
        { name: "admin"; isMut: false; isSigner: true },
        { name: "platformState"; isMut: true; isSigner: false }
      ];
      args: [{ name: "newApyBps"; type: "u64" }];
    },
    {
      name: "setReferralRates";
      accounts: [
        { name: "admin"; isMut: false; isSigner: true },
        { name: "platformState"; isMut: true; isSigner: false }
      ];
      args: [{ name: "newRatesBps"; type: { array: ["u64", 10] } }];
    },
    {
      name: "blockUser";
      accounts: [
        { name: "admin"; isMut: false; isSigner: true },
        { name: "platformState"; isMut: false; isSigner: false },
        { name: "userStakeAccount"; isMut: true; isSigner: false }
      ];
      args: [{ name: "targetUser"; type: "publicKey" }];
    },
    {
      name: "unblockUser";
      accounts: [
        { name: "admin"; isMut: false; isSigner: true },
        { name: "platformState"; isMut: false; isSigner: false },
        { name: "userStakeAccount"; isMut: true; isSigner: false }
      ];
      args: [{ name: "targetUser"; type: "publicKey" }];
    },
    {
      name: "setPauseState";
      accounts: [
        { name: "admin"; isMut: false; isSigner: true },
        { name: "platformState"; isMut: true; isSigner: false }
      ];
      args: [{ name: "paused"; type: "bool" }];
    },
    {
      name: "transferAdmin";
      accounts: [
        { name: "admin"; isMut: false; isSigner: true },
        { name: "platformState"; isMut: true; isSigner: false }
      ];
      args: [{ name: "newAdmin"; type: "publicKey" }];
    }
  ];
  accounts: [
    {
      name: "PlatformState";
      type: {
        kind: "struct";
        fields: [
          { name: "admin"; type: "publicKey" },
          { name: "tokenMint"; type: "publicKey" },
          { name: "vault"; type: "publicKey" },
          { name: "rewardVault"; type: "publicKey" },
          { name: "totalStaked"; type: "u64" },
          { name: "totalRewardsPaid"; type: "u64" },
          { name: "baseApyBps"; type: "u64" },
          { name: "referralRatesBps"; type: { array: ["u64", 10] } },
          { name: "isPaused"; type: "bool" },
          { name: "totalStakers"; type: "u64" },
          { name: "bump"; type: "u8" }
        ];
      };
    },
    {
      name: "UserStakeAccount";
      type: {
        kind: "struct";
        fields: [
          { name: "user"; type: "publicKey" },
          { name: "amountStaked"; type: "u64" },
          { name: "lockPeriodSecs"; type: "u64" },
          { name: "stakeTimestamp"; type: "i64" },
          { name: "lastClaimTimestamp"; type: "i64" },
          { name: "referrer"; type: "publicKey" },
          { name: "referralChain"; type: { array: ["publicKey", 10] } },
          { name: "accruedRewards"; type: "u64" },
          { name: "totalRewardsClaimed"; type: "u64" },
          { name: "totalReferralEarned"; type: "u64" },
          { name: "pendingReferralRewards"; type: "u64" },
          { name: "isBlocked"; type: "bool" },
          { name: "isActive"; type: "bool" },
          { name: "bump"; type: "u8" }
        ];
      };
    }
  ];
  errors: [
    { code: 6000; name: "InvalidLockPeriod"; msg: "Invalid lock period." },
    { code: 6001; name: "TokensStillLocked"; msg: "Tokens are still locked." },
    { code: 6002; name: "NoActiveStake"; msg: "No active stake found." },
    { code: 6003; name: "AlreadyStaked"; msg: "User already has an active stake." },
    { code: 6004; name: "InsufficientRewardPool"; msg: "Insufficient reward pool balance." },
    { code: 6005; name: "NoRewardsToClaim"; msg: "No rewards available to claim." },
    { code: 6006; name: "UserBlocked"; msg: "User is blocked from this platform." },
    { code: 6007; name: "Unauthorized"; msg: "Unauthorized." },
    { code: 6008; name: "SelfReferral"; msg: "Cannot refer yourself." },
    { code: 6009; name: "ReferrerNotStaked"; msg: "Referrer has no active stake." },
    { code: 6010; name: "ArithmeticOverflow"; msg: "Arithmetic overflow." },
    { code: 6011; name: "InvalidRewardRate"; msg: "Invalid reward rate." },
    { code: 6012; name: "ZeroStakeAmount"; msg: "Stake amount must be > 0." },
    { code: 6013; name: "PlatformPaused"; msg: "Platform is currently paused." },
    { code: 6014; name: "ClaimCooldown"; msg: "Claim cooldown not elapsed." }
  ];
};

export const IDL: Staking = {
  version: "0.1.0",
  name: "staking",
  instructions: [] as any,
  accounts: [] as any,
  errors: [] as any,
};
